### ISSUE TITLE
get_neighborhood(....) suggestion

### ISSUE THREAD

**Issue by lonnieOST** [IntelLabs/pmgd#27]
Hello,

I really like the way that the nodes and edges methods work

db.get_nodes(...)
db.get_edges(...)

and am becoming fond of this type of Iterator:

NodeIterator pi = db.get_nodes("Person", PropertyPredicate{ "Name", PropertyPredicate::Eq, "John" });

In trying to work with nodes, edges, and neighborhoods I would like to suggest the addition of perhaps something like this as well:

NodeIterator pi = db.get_neighbors( *mi, "Person", PropertyPredicate{ "Name", PropertyPredicate::Eq, "John" });

and

NodeIterator pi = db.get_neighbors(*mi, PropertyPredicate{ "Name", PropertyPredicate::Eq, "John" });

where get_neighbors() would look at the

 NeighborhoodIterator get_neighborhood
    (const PMGD::Node &node, int max_hops, StringID tag, const PropertyPredicate &, bool reverse = false)

There could be a number of methods for this implementation, but I would find it particularly useful to have one like I mentioned above so that get_neighborhood() could collect neighbors with a particular "StringID tag", and "const PropertyPredicate &" such that I could have finer-grained control over which neighbors would be returned.

What is the possibility of getting something like this added to the latest "development" version?
Cheers and have a great day

**Comment by philiplantz** [comment]
Since there are no indices on the edge list of a node, there is no ability for PMGD to optimize the search you have described. So you can get the same performance with;

```
NodeIterator pi = get_neighbors(node, edge_tag)
    .filter(PropertyPredicate{ "Name", PropertyPredicate::Eq, "John" });
```

By implementing exactly what you need in your application you may in fact may achieve better performance than using a general-purpose function.

You can also create a filter function specific to your query:

```
StringID node_tag("Person");
StringID property_name("Name");
std::string search_value("John");
NodeIterator pi = get_neighbors(node, edge_tag)
    .filter([node_tag, property_name, search_value](const Node &n) {
          return n.get_tag() == node_tag && get_property(property_name).string_value() == search_value; });
```

The filter function can return one the following:
DontPass: skip this node and keep going
Pass: use this node and keep going
Stop: don't use this node or any subsequent nodes
PassStop: use this node but no subsequent nodes

DontPass and Pass have value 0 and 1, so you can write a function that returns bool, as I did above, if you don't need to use the Stop options.

I used StringID objects rather than explicit strings for the tag and property ids, to avoid the string lookup every time.

P.S. The get_neighbors functions are not members of Graph.
